before_script:
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apk update -y && apk add openssh-client git -y )'
    # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  - echo hostname
  - rm -rf ~/.ssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'deploy.blueclerk.com' >> ~/.ssh/known_hosts

stages:
  - dev

deploy_to_dokku:
  stage: dev
  script:
    - git checkout dev
    - git push dokku@deploy.blueclerk.com:blueclerk-frontend-dev origin/dev:refs/heads/master